pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "web_test_automation"
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Checking out the repository...'
                checkout([$class: 'GitSCM',
                          branches: [[name: 'main']],
                          userRemoteConfigs: [[url: 'https://github.com/Jubear-Jabber-Jetu/Docker_Email_Send.git',
                                               credentialsId: 'github']]])
            }
        }
        
        stage('Build Docker Image') {
            steps {
                echo 'Building the Docker image...'
                script {
                    try {
                        powershell '''
                            docker build -t $Env:DOCKER_IMAGE .
                        '''
                    } catch (Exception e) {
                        echo "Error building Docker image: ${e.message}"
                        currentBuild.result = 'FAILURE'
                        error "Stopping pipeline execution due to Docker build failure"
                    }
                }
            }
        }
