version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/openjdk:11-jdk

jobs:
  checkout:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Checking out the repository
          command: echo 'Checking out the repository...'

  build_docker_image:
    executor: docker-executor
    steps:
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - checkout
      - run:
          name: Build Docker Image
          command: docker build -t web_test_automation .

  run_tests_in_docker:
    executor: docker-executor
    steps:
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - checkout
      - run:
          name: Run Tests in Docker Container
          command: |
            docker run --rm -v $CIRCLE_WORKING_DIRECTORY/test-results:/app/test-results web_test_automation sh -c "mvn clean test || true"
      - store_test_results:
          path: test-results  # Directory where JUnit XML results are saved
      - store_artifacts:
          path: test-results  # Save test results as artifacts

  run_newman_tests:
    executor: docker-executor
    steps:
      - run:
          name: Install Newman
          command: |
            npm install -g newman
      - run:
          name: Run Newman Tests
          command: |
            newman run /path/to/your/collection.json -r html,json --reporter-html-export newman-report.html --reporter-json-export newman-report.json
      - store_artifacts:
          path: newman-report.html  # Save Newman HTML report as artifact
      - store_artifacts:
          path: newman-report.json  # Save Newman JSON report as artifact

workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout
      - build_docker_image:
          requires:
            - checkout
      - run_tests_in_docker:
          requires:
            - build_docker_image
      - run_newman_tests:
          requires:
            - build_docker_image
