version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/openjdk:11-jdk
        auth:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_PASSWORD

jobs:
  checkout:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Checking out the repository
          command: echo 'Checking out the repository...'

workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout
