version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/openjdk:11-jdk

jobs:
  checkout:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Checking out the repository
          command: echo 'Checking out the repository...'

  build_docker_image:
    executor: docker-executor
    steps:
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - checkout
      - run:
          name: Build Docker Image
          command: docker build -t web_test_automation .

  run_tests_in_docker:
    executor: docker-executor
    steps:
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - checkout
      - run:
          name: Run Tests in Docker Container
          command: |
            docker run --rm -v $CIRCLE_WORKING_DIRECTORY/allure-results:/app/allure-results web_test_automation sh -c "mvn clean test"
      - store_test_results:
          path: allure-results  # Update this path if your results are in a different directory

  generate_report_summary:
    executor: docker-executor
    steps:
      - run:
          name: Install JUnit Report Aggregator (Optional)
          command: |
            # If you need specific tools for report aggregation, install them here
            echo "JUnit report aggregation is handled by CircleCI natively."
      - run:
          name: Generate Report Summary
          command: |
            echo "CircleCI handles test result summarization natively."
      - store_artifacts:
          path: allure-results  # Optional: Store raw test result files if needed

workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout
      - build_docker_image:
          requires:
            - checkout
      - run_tests_in_docker:
          requires:
            - build_docker_image
      - generate_report_summary:
          requires:
            - run_tests_in_docker
