version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/openjdk:11-jdk

jobs:
  checkout:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Checking out the repository
          command: echo 'Checking out the repository...'

  build_docker_image:
    executor: docker-executor
    steps:
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - checkout
      - run:
          name: Build Docker Image
          command: docker build -t web_test_automation .

  run_tests_in_docker:
    executor: docker-executor
    steps:
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - checkout
      - run:
          name: Run Tests in Docker Container
          command: |
            docker run --rm -v $CIRCLE_WORKING_DIRECTORY/test-results:/app/test-results web_test_automation sh -c "mvn clean test"
      - run:
          name: Generate Custom Report
          command: |
            # Custom reporting script
            python generate_report.py  # Example script to generate a custom report
      - store_artifacts:
          path: custom-report.html  # Save custom HTML report as artifact
      - store_artifacts:
          path: custom-report.json  # Save custom JSON report as artifact

workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout
      - build_docker_image:
          requires:
            - checkout
      - run_tests_in_docker:
          requires:
            - build_docker_image
