version: 2.1

# Define a job to be invoked later in a workflow.
jobs:
  build-and-test:
    docker:
      - image: cimg/maven:3.8.4

    steps:
      - checkout
      - run:
          name: "Build and Test Maven Project"
          command: |
            mvn clean install

# Orchestrate jobs using workflows
workflows:
  build-and-test-workflow:
    jobs:
      - build-and-test
