version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/openjdk:11-jdk

jobs:
  checkout:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Checking out the repository
          command: echo 'Checking out the repository...'

  build_docker_image:
    executor: docker-executor
    steps:
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - checkout
      - run:
          name: Build Docker Image
          command: docker build -t web_test_automation .

  run_tests_in_docker:
    executor: docker-executor
    steps:
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - checkout
      - run:
          name: Run Tests in Docker Container
          command: |
            docker run --rm -v $CIRCLE_WORKING_DIRECTORY/test-results:/app/test-results web_test_automation sh -c "mvn clean test"
      - store_test_results:
          path: test-results  # Directory where JUnit XML results are saved
      - store_artifacts:
          path: test-results  # Save test results as artifacts

  generate_code_coverage_report:
    executor: docker-executor
    steps:
      - run:
          name: Generate Code Coverage Report
          command: |
            mvn clean test
            mvn jacoco:report
      - store_artifacts:
          path: target/site/jacoco  # Save JaCoCo HTML report as artifact
      - store_artifacts:
          path: target/jacoco.exec  # Save JaCoCo binary coverage data

  snyk_security_scan:
    executor: docker-executor
    steps:
      - run:
          name: Install Snyk
          command: npm install -g snyk
      - run:
          name: Run Snyk Security Scan
          command: snyk test --json > snyk-report.json
      - store_artifacts:
          path: snyk-report.json  # Save Snyk JSON report as artifact

workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout
      - build_docker_image:
          requires:
            - checkout
      - run_tests_in_docker:
          requires:
            - build_docker_image
      - generate_code_coverage_report:
          requires:
            - run_tests_in_docker
      - snyk_security_scan:
          requires:
            - build_docker_image
