version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/openjdk:11-jdk

jobs:
  setup_xvfb:
    executor: docker-executor
    steps:
      - run:
          name: Install Xvfb
          command: |
            apt-get update && apt-get install -y xvfb
      - run:
          name: Start Xvfb
          command: |
            Xvfb :99 -screen 0 1280x1024x24 &

  checkout:
    executor: docker-executor
    steps:
      - checkout

  build_docker_image:
    executor: docker-executor
    steps:
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - checkout
      - run:
          name: Build Docker Image
          command: docker build -t web_test_automation .

  run_tests_in_docker:
    executor: docker-executor
    steps:
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - checkout
      - run:
          name: Run Tests in Docker Container
          command: |
            DISPLAY=:99 docker run --rm web_test_automation sh -c "mvn clean test"

workflows:
  version: 2
  build_and_test:
    jobs:
      - setup_xvfb
      - checkout:
          requires:
            - setup_xvfb
      - build_docker_image:
          requires:
            - checkout
      - run_tests_in_docker:
          requires:
            - build_docker_image
