version: 2.1

jobs:
  build:
    docker:
      - image: your-docker-image:latest  # Replace with your Docker image tag
    steps:
      - checkout
      - run:
          name: Build with Maven
          command: mvn clean install
workflows:
  version: 2
  build:
    jobs:
      - build
