version: 2.1

executors:
  windows-executor:
    docker:
      - image: mcr.microsoft.com/windows/servercore:ltsc2019  # or any suitable Windows image

jobs:
  checkout:
    executor: windows-executor
    steps:
      - checkout
      - run:
          name: Checkout the repository
          command: echo "Checking out the repository..."

  build_docker_image:
    executor: windows-executor
    steps:
      - run:
          name: Build Docker Image
          command: docker build -t web_test_automation .

  run_tests_in_docker:
    executor: windows-executor
    steps:
      - run:
          name: Run Tests in Docker Container
          command: |
            docker run --rm -v %CD%\allure-results:/app/allure-results web_test_automation sh -c "mvn clean test || true"

  generate_allure_report:
    executor: windows-executor
    steps:
      - run:
          name: Install Allure Commandline
          command: |
            powershell -Command "Invoke-WebRequest -Uri 'https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.14.0/allure-commandline-2.14.0.zip' -OutFile 'allure-commandline.zip'"
            powershell -Command "Expand-Archive -Path 'allure-commandline.zip' -DestinationPath 'C:\Program Files\Allure'"
            powershell -Command "set-location 'C:\Program Files\Allure\allure-commandline-2.14.0\bin'; [System.Environment]::SetEnvironmentVariable('PATH', $env:PATH + ';' + (Get-Location).Path, [System.EnvironmentVariableTarget]::Machine)"
      - run:
          name: Generate Allure Report
          command: |
            allure generate allure-results --clean -o allure-report
      - store_artifacts:
          path: allure-report
          destination: allure-report
      - store_test_results:
          path: allure-results

workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout
      - build_docker_image:
          requires:
            - checkout
      - run_tests_in_docker:
          requires:
            - build_docker_image
      - generate_allure_report:
          requires:
            - run_tests_in_docker
