version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/openjdk:11-jdk

jobs:
  checkout:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Checking out the repository
          command: echo 'Checking out the repository...'

  build_docker_image:
    executor: docker-executor
    steps:
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - checkout
      - run:
          name: Build Docker Image
          command: docker build -t web_test_automation .

  run_tests_in_docker:
    executor: docker-executor
    steps:
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - checkout
      - run:
          name: Run Tests in Docker Container
          command: |
            docker run --rm -v $CIRCLE_WORKING_DIRECTORY/allure-results:/app/allure-results web_test_automation sh -c "mvn clean test || true"

  generate_allure_report:
    executor: docker-executor
    steps:
      - run:
          name: Install Allure Commandline
        command: |
            sudo apt-get update
            sudo apt-get install -y allure
      - run:
          name: Generate Allure Report
          command: |
            allure generate $CIRCLE_WORKING_DIRECTORY/allure-results --clean -o $CIRCLE_WORKING_DIRECTORY/allure-report
      - store_artifacts:
          path: allure-report
          destination: allure-report
      - store_test_results:
          path: allure-results

workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout
      - build_docker_image:
          requires:
            - checkout
      - run_tests_in_docker:
          requires:
            - build_docker_image
      - generate_allure_report:
          requires:
            - run_tests_in_docker
