version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/maven:3.8.4

    steps:
      - checkout
      - run:
          name: "Build and Test Maven Project"
          command: |
            mvn clean install

workflows:
  build-and-test-workflow:
    jobs:
      - build-and-test
